secret:
    dbHost: ENC[AES256_GCM,data:8g39nmrN7a4=,iv:PG7gcG9fOnXMThd7Qamjt2wdFBjiL3JQ9pQQEwIm6wk=,tag:YHwjQYdiUxJSnP0k7u/iCQ==,type:str]
    dbPort: ENC[AES256_GCM,data:6mdOwg==,iv:yLK3AA8ZIVpF/xZjxiWrR6BD4QomRFIEiL9ME+r9XyI=,tag:aKJm3qUV+6tbrmIhtd9vQQ==,type:str]
    dbUser: ENC[AES256_GCM,data:9bDPxFg=,iv:AHnREATZAOxmtWew6cCcf2fXDPsH1c6S+752+8kPWUM=,tag:ob5/6g8I7N3ewuG4sooYMg==,type:str]
    dbPassword: ENC[AES256_GCM,data:FFDI7VFzIZrsTC8=,iv:ngxfWyREhLm6Wvu1UmaHiJFOAJ3q64s18B4NTg0DVgI=,tag:pho+X3NBAUmSbAlkkh16Nw==,type:str]
    dbName: ENC[AES256_GCM,data:Zyhupw==,iv:JLTPdAHnhtr363B7yPxgUFgWctRV1N+plUCm91ovGCA=,tag:tWPQzbCTB4iyGdgFkpNBGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSS2tVVVVEeEMvM1NMMFJ6
            QWlIaElFRUhYSFZvQ3VERkxSVWVvVDFya0ZnCmpZTVVSalFBeVlDcmJaZXY3aGF6
            TElqV3Z2ZWRUdkMvRnQxTjErY1E4WXcKLS0tIFREazZNRXorTmcyV1d0QnNxaWV3
            Wm9wRVhpZFhKRUtGNFU4b09OalloTjQKQHqIdl5a1sXvvV59CxeZv2BAEp7pE9f0
            JfOunuwo5jeEWd7Hryx9WbknPF4n3tvONKf1DSzQlffvo+20QlPHOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pumvr3apvrfje8fvhuqk5tf5jnken5hafz9hq66uwftnaka3cdvskrjys9
    lastmodified: "2026-07-26T10:41:19Z"
    mac: ENC[AES256_GCM,data:4liNMepUwbe7JT+RxHSXBK7tdh1a7ym5uPChcRv469IpQs4P0qVfRlFugq3mtb3tcNphn5cUTEj42krr07hEMc6QYNvZB0ELUZRIKIiwDFBWDXulKiBgWSbv6fR6IOJ4KvwVWp9A2zqyY6EJ5X3g9qzKJhV+DJTgmkAvNWQ38Ds=,iv:/USu/dAMdVwRxvv6R/rPEJphMn5CAZg3FHJThHzf2t8=,tag:4P9cUFHAgiuVTFvUh1Sjkg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
