name: devsops-lessons
# db
services:
  db: 
    image: ${DOCKER_IMAGE_DB}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    # ports:
    #   - "${DB_PORT}:${DB_PORT}"
    networks:
      - internal

# db client
  dbeaver:
    image: dbeaver/cloudbeaver:26.0.5
    ports:
      - "127.0.0.1:${DB_CLIENT_HOST_PORT}:${DB_CLIENT_PORT}"
    volumes:
      - cdbeaver:/opt/cloudbeaver/workspace
    depends_on:
      - db
    networks:
      - internal
      - public
    
  # main backend
  backend:
    image: ${DOCKER_IMAGE_BE}
    restart: always
    environment:
      PORT: ${PORT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "127.0.0.1:${HOST_PORT}:${PORT}"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:$PORT/api/health | grep -q '\"status\":\"ok\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - public

  frontend:
    image: ${DOCKER_IMAGE_FE}
    ports:
    # Докер когда мы мапим порнты с хоста на арпт внутри контейнера, докер создает запись в IP tables минуя фаервол пропуская запросы снаружи.
    # поэтому мы явно указываем 127.0.0.1 это означает что доступ к этому порту мы имеем только с локальной машины, а не снаружи. Все запросы снаружи пойдут через nginx который будет проксировать запросы на фронтенд.
      - "127.0.0.1:${FE_HOST_PORT}:${FE_PORT}"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - public

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    pid: host                          # доступ к PID-пространству хоста
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - public


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'   # хранить данные 15 дней
    restart: unless-stopped
    networks:
      - public


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - public


  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yml
    restart: unless-stopped
    networks:
      - public
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail # нужен чтобы читать логи других контейнеров и работать с Docker-сокетом.
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true
    restart: unless-stopped
    networks:
      - public

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - app-network


networks:
  internal:
    # no access from outside
    internal: true
  public:

volumes:
  pgdata:
  cdbeaver:
  prometheus_data:
  grafana_data:
  loki_data:
  portainer_data: