name: devsops-lessons
# db
services:
  db: 
    image: ${DOCKER_IMAGE_DB}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    # ports:
    #   - "${DB_PORT}:${DB_PORT}"
    networks:
      - internal

# db client
  dbeaver:
    image: dbeaver/cloudbeaver:26.0.5
    ports:
      - "${DB_CLIENT_HOST_PORT}:${DB_CLIENT_PORT}"
    volumes:
      - cdbeaver:/opt/cloudbeaver/workspace
    depends_on:
      - db
    networks:
      - internal
      - public
    
  # main backend
  backend:
    image: ${DOCKER_IMAGE_BE}
    restart: always
    environment:
      PORT: ${PORT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${HOST_PORT}:${PORT}"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:$PORT/api/health | grep -q '\"status\":\"ok\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - public

  frontend:
    image: ${DOCKER_IMAGE_FE}
    ports:
      - "${FE_HOST_PORT}:${FE_PORT}"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - public

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    pid: host                          # доступ к PID-пространству хоста
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - public


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'   # хранить данные 15 дней
    restart: unless-stopped
    networks:
      - public


networks:
  internal:
    # no access from outside
    internal: true
  public:

volumes:
  pgdata:
  cdbeaver:
  prometheus_data: