apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      imagePullSecrets:
        - name: dockerhub-cred
      containers:
      - name: backend-api
        image: ${IMAGE}
        resources:
          requests:
            cpu: "140m"
            memory: "200Mi"
          limits:
            cpu: "160m"
            memory: "240Mi"
        ports:
          - containerPort: 3005
        envFrom:
          - configMapRef:
              name: backend-config
          - secretRef:
              name: backend-secret