apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: fenix4088/lessons-todo-back:latest
        ports:
          - containerPort: 3005
        env:
          - name: DB_HOST
            value: "postgres"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "shop"
          - name: DB_USER
            value: "admin"
          - name: DB_PASSWORD
            value: "supersecret"