apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-cred
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "fenix4088",
          "password": "dckr_pat_ckpYFuMHbK6WKX5-LeKuEyO34pM"
        }
      }
    }