secret:
    dbName: ENC[AES256_GCM,data:L7U0KA==,iv:tZaQY2ejMf3pTP5IraBx+l20U+44rXHLnyS2m8ciy+M=,tag:zZ/rzDrOWnZqbZQ6nFAHmg==,type:str]
    dbUser: ENC[AES256_GCM,data:6E+7wY8=,iv:Gnm6kzct1Qsp0Rch9c6aRO0WEIcP+W3iH5wSSeWGSSM=,tag:q42S4ee6tqehdu6Ncc/PsA==,type:str]
    dbPassword: ENC[AES256_GCM,data:/f8C893fiZEMiRA=,iv:rQE/WY7bcnKlimfbBise2E6fQhuSXEhqc522l0mXP4I=,tag:GNJHQz0k+IP1uK/nScrDzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cytjblpHZjlWWmJjb1Ft
            VFdiSklnWm85Ymc4MHA1WTlObHppcG9ZWUY0CjlveXMzNTE5dHQ5eEJvYnNrLzFy
            Uy9acFkzc241UmQ4dnA1TFBRbUtSWXcKLS0tIGxXNHVNei9SV3B2aGFKQzlWOXR6
            dlg0RVBIWjI4a0FRMFM3YUF4M056R3MKjH/SSHa7m2vbn9/eiZZfpaMN54BaFbFD
            VlRCEE7Q6b7b9rGlPCzSIZusdpN5w/6LEAJx8Z8gO4mui89UcIcIiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pumvr3apvrfje8fvhuqk5tf5jnken5hafz9hq66uwftnaka3cdvskrjys9
    lastmodified: "2026-07-26T10:41:03Z"
    mac: ENC[AES256_GCM,data:vYjXz59bnS9B+CZJbFRyH5P/foFXEdphqRyt8W4tGD19YvQbkuohXHE68IybIKAYtbRy6Q4yNlfCDRhE3hsiic0jr4NWkHBnYyE+fkXW1LxmBlo8s3QhUP4AzAcooqOB0LwSnHIuIQJr+rzxc7vfW5Njf/JX73SbZ421xvM8Drw=,iv:zrmcrHDyeD/z9Gp3wnYwz/DJeD8UH4qUHpyM2nTMW/0=,tag:2NobAry4RgixY/MQmFzbJQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
