name: Deploy
 
on:
  push:
    branches: [main]
 
jobs:
  checks:
    uses: ./.github/workflows/pr-check.yml
 
  deploy:
    needs: checks
    runs-on: ubuntu-latest
 
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/devops-lessons
            git pull origin main
            cd /var/www/lessons
            docker compose up --build -d
  notify:
    if: always()
    needs: [checks, deploy]
    uses: ./.github/workflows/notify.yml
    with:
      checks_status: ${{ needs.checks.result }}
      deploy_status: ${{ needs.deploy.result }}
      backend_result: ${{ needs.checks.outputs.backend_result }}
      test_result: ${{ needs.checks.outputs.test_result }}
      frontend_result: ${{ needs.checks.outputs.frontend_result }}
    secrets: inherit
